-- 0033: a starter list of sights. Admins add, rename and hide entries at
-- /admin/sights; this only fills an empty platform.
insert into sights (name_hy, name_ru, name_en, region) values
  ('Արագած լեռ', 'Гора Арагац', 'Mount Aragats', 'aragatsotn'),
  ('Քարի լիճ', 'Озеро Кари', 'Lake Kari', 'aragatsotn'),
  ('Ամբերդ ամրոց', 'Крепость Амберд', 'Amberd Fortress', 'aragatsotn'),
  ('Սաղմոսավանք և Քասաղի կիրճ', 'Сагмосаванк и Касахское ущелье', 'Saghmosavank and the Kasagh Gorge', 'aragatsotn'),
  ('Հովհաննավանք', 'Ованаванк', 'Hovhannavank', 'aragatsotn'),
  ('Արա լեռ', 'Гора Ара', 'Mount Ara', 'aragatsotn'),
  ('Արտենի լեռ', 'Гора Артени', 'Mount Arteni', 'aragatsotn'),
  ('Խոր Վիրապ', 'Хор Вирап', 'Khor Virap', 'ararat'),
  ('Խոսրովի անտառ', 'Хосровский лес', 'Khosrov Forest', 'ararat'),
  ('Վեդիի կիրճ', 'Ущелье Веди', 'Vedi Gorge', 'ararat'),
  ('Զվարթնոց', 'Звартноц', 'Zvartnots', 'armavir'),
  ('Սարդարապատ', 'Сардарапат', 'Sardarapat', 'armavir'),
  ('Սևանա լիճ', 'Озеро Севан', 'Lake Sevan', 'gegharkunik'),
  ('Սևանավանք', 'Севанаванк', 'Sevanavank', 'gegharkunik'),
  ('Հայրավանք', 'Айраванк', 'Hayravank', 'gegharkunik'),
  ('Նորատուսի խաչքարեր', 'Хачкары Норатуса', 'Noratus Khachkars', 'gegharkunik'),
  ('Աժդահակ լեռ', 'Гора Аждаак', 'Mount Azhdahak', 'gegharkunik'),
  ('Արմաղան լեռ', 'Гора Армаган', 'Mount Armaghan', 'gegharkunik'),
  ('Գառնու տաճար', 'Храм Гарни', 'Garni Temple', 'kotayk'),
  ('Քարերի սիմֆոնիա', 'Симфония камней', 'Symphony of Stones', 'kotayk'),
  ('Գեղարդ', 'Гегард', 'Geghard', 'kotayk'),
  ('Հատիս լեռ', 'Гора Атис', 'Mount Hatis', 'kotayk'),
  ('Թեղենիս լեռ', 'Гора Тегенис', 'Mount Teghenis', 'kotayk'),
  ('Բջնի ամրոց', 'Крепость Бджни', 'Bjni Fortress', 'kotayk'),
  ('Ծաղկաձոր', 'Цахкадзор', 'Tsaghkadzor', 'kotayk'),
  ('Հաղպատ', 'Ахпат', 'Haghpat', 'lori'),
  ('Սանահին', 'Санаин', 'Sanahin', 'lori'),
  ('Ախթալա', 'Ахтала', 'Akhtala', 'lori'),
  ('Օձուն', 'Одзун', 'Odzun', 'lori'),
  ('Լոռի բերդ', 'Лори берд', 'Lori Berd', 'lori'),
  ('Ստեփանավանի դենդրոպարկ', 'Дендропарк Степанавана', 'Stepanavan Dendropark', 'lori'),
  ('Թռչկանի ջրվեժ', 'Водопад Трчкан', 'Trchkan Waterfall', 'shirak'),
  ('Մարմաշեն', 'Мармашен', 'Marmashen', 'shirak'),
  ('Արփի լիճ', 'Озеро Арпи', 'Lake Arpi', 'shirak'),
  ('Տաթև և Տաթևի թևեր', 'Татев и «Крылья Татева»', 'Tatev and the Wings of Tatev', 'syunik'),
  ('Սատանի կամուրջ', 'Чёртов мост', 'Devil''s Bridge', 'syunik'),
  ('Խնձորեսկ', 'Хндзореск', 'Khndzoresk', 'syunik'),
  ('Շաքիի ջրվեժ', 'Водопад Шаки', 'Shaki Waterfall', 'syunik'),
  ('Զորաց քարեր', 'Зорац Карер', 'Zorats Karer', 'syunik'),
  ('Ուխտասար', 'Ухтасар', 'Ughtasar', 'syunik'),
  ('Խուստուփ լեռ', 'Гора Хуступ', 'Mount Khustup', 'syunik'),
  ('Նորավանք', 'Нораванк', 'Noravank', 'vayots_dzor'),
  ('Ջերմուկի ջրվեժ', 'Джермукский водопад', 'Jermuk Waterfall', 'vayots_dzor'),
  ('Սմբատաբերդ', 'Смбатаберд', 'Smbataberd', 'vayots_dzor'),
  ('Արենիի քարանձավ', 'Пещера Арени', 'Areni Cave', 'vayots_dzor'),
  ('Գնդեվանք', 'Гндеванк', 'Gndevank', 'vayots_dzor'),
  ('Սելիմի քարավանատուն', 'Селимский караван-сарай', 'Selim Caravanserai', 'vayots_dzor'),
  ('Դիլիջանի ազգային պարկ', 'Дилижанский национальный парк', 'Dilijan National Park', 'tavush'),
  ('Պարզ լիճ', 'Озеро Парз', 'Lake Parz', 'tavush'),
  ('Գոշ լիճ և Գոշավանք', 'Озеро Гош и Гошаванк', 'Lake Gosh and Goshavank', 'tavush'),
  ('Հաղարծին', 'Агарцин', 'Haghartsin', 'tavush'),
  ('Լաստիվեր', 'Ластивер', 'Lastiver', 'tavush'),
  ('Ենոքավան', 'Енокаван', 'Yenokavan', 'tavush'),
  ('Դիմաց լեռ', 'Гора Димац', 'Mount Dimats', 'tavush'),
  ('Էրեբունի ամրոց', 'Крепость Эребуни', 'Erebuni Fortress', 'yerevan')
on conflict (name_hy) do nothing;
